spring:
  profiles:
    active: dev

root:
  correlationid: photographer-master-service
  service:
    name: Photographer Master Service
    description: Photographer Master Service to maintain photographer details
    version: v1
    usage: Proprietary Usage
    owner: Balarka Brahma
    website: NA
    officialemail: balarka.brahma@gmail.com
    license: Public API Lincense
    baseurl: /service/fotos
    moduleurl: ${service.baseuri}/photog/${root.service.version}

