spring:
  profiles:
    active: dev

root:
  correlationid: photographer-master-service
  service:
    name: Photographer Master Service
    description: Photographer Master Service to keep the photographer details
    version: v1
    usage: Proprietary Usage
    owner: Balarka Brahma
    website: NA
    officialemail: balarka.brahma@gmail.com
    license: NA