spring:
  profiles:
    active: dev
  application:
    name: photographer-master-service
  zipkin:
    base-url: http://localhost:9411/

root:
  service:
    name: Photographer Master Service
    description: Photographer Master Service to maintain photographer details
    version: v1
    usage: Proprietary Usage
    owner: Balarka Brahma
    website: NA
    officialemail: balarka.brahma@gmail.com
    license: Public API Lincense
    baseurl: /service/fotos
    moduleurl: ${root.service.baseurl}/${root.service.version}/photographer

