server:
  port: 8010

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/photographer
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      fotos:
        photographer:
          master:
            service: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG