server:
  port: 9000
  
#  ssl:
#    key-alias: book-master-service
#    key-store-type: JKS
#   key-password: password
#   key-store-password: password
#   key-store: classpath:book-master-service.jks
  
spring:
  application:
    name: book-edge-service
    
  cloud:
    gateway:
      routes:
      - id: book-service-find-all-route
        uri: ${BOOK_SERVEICE_URL:https://localhost:8010}
        predicates:          - Path=/service/book/all
        filters:          - name: Retry
            args:              retries: 3
              methods: GET
              backoffs:
                firstBackoffs: 50ms
                maxBackoffs: 500ms
                
      - id: book-service-find-title-author-route
        uri: ${BOOK_SERVEICE_URL:https://localhost:8010}
        predicates:
          - Path=/service/book/
        filters:
          - name: Retry
            args:
              retries: 3
              methods: GET
              backoffs:
                firstBackoffs: 50ms
                maxBackoffs: 500ms
            
      - id: book-service-find-id-route
        uri: ${BOOK_SERVEICE_URL:https://localhost:8010}
        predicates:
          - Path=/service/book/{id}
        filters:
          - name: Retry
            args:
              retries: 3
              methods: GET
              backoffs:
                firstBackoffs: 50ms
                maxBackoffs: 500ms
                
      - id: book-service-save-route
        uri: ${BOOK_SERVEICE_URL:https://localhost:8010}
        predicates:
          - Path=/service/book/save
       
                
                
                
                