spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: root
  jpa:     hibernate:      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true

server:  port: 8010
  
bookdetails:
  info:    
    correlationid: BOOK-DETAILS_SERVICE-01
    service:
      name: Book Details Service
      description: Book Details API to manage book master details
      version: v1
      usage: Proprietary Usage
      owner: Balarka Brahma
      website: https://www.balarkabrahma.com
      officialemail: balarka.brahma@gmail.com
      license: Public API Lincense 
  
service:
  baseuri: /service/book
  activeversion: v1
  moduleuri: ${service.baseuri}/deviceinfo/${service.activeversion}






#  ssl:
#    key-alias: book-master-service
#   key-store-type: JKS
#   key-password: password
#   key-store-password: password
#   key-store: classpath:book-master-service.jks
  